### PR TITLE
API: fix #27

### LINKED ISSUE #27: API: payload for ModifyEmoji always empty
The payload sent by `api.Client.ModifyEmoji` is always empty, as the param struct is initialized with zero values, but the values passed to the method never get assigned to the payload.

I will create a PR fixing this.

### PR DESCRIPTION
**Pull request by mavolin**
Closes #27.

### CODE REVIEW

**Comment by mavolin** [comment]
I also found that the `ErrEmojiTooLarge` variable in the same file is unused. Should I create a commit removing that?

**Comment by diamondburned** [comment]
> I also found that the `ErrEmojiTooLarge` variable in the same file is unused. Should I create a commit removing that?

Yes, that should be removed. I suppose it was meant to be used with `image.Validate()`, but that already has its own error.

**Comment by mavolin** [comment]
Done. Could you, if possible, release a hotfix release for this, as I need this method for a project I am working on.

**Comment by diamondburned** [comment]
Will do as soon as CI passes.

**Pull request merged**
